language: ruby
branches:
  only:
    - master
    - stable
env:
  global:
    - HEADLESS=true
    - RAILS_DB_ADAPTER=mysql2
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - 2.3.1
  - 2.4.0
matrix:
  allow_failures:
    - rvm: 2.4.0
install:
  - cd .. && git clone https://github.com/hitobito/hitobito.git hitobito
  - cd hitobito && git checkout -f $([[ $TRAVIS_BRANCH = 'stable' ]] && echo 'stable' || echo 'master')
  - sed -i "s/^\(gem .mysql2.\),.*$/\1/" Gemfile
  - cp -v Wagonfile.ci Wagonfile
  - rvm use $TRAVIS_RUBY_VERSION
  - bundle install --path vendor/bundle
  - bundle update mysql2
  - for d in ../hitobito_*; do cp -v Gemfile.lock $d; done
  - rm -rf tmp/tarantula
script:
  - bundle exec rake db:create ci:wagon --trace
